import Head from 'next/head'
import {
  useEffect
} from 'react'
import {
  useRouter
} from 'next/router'
import Image from 'next/image'
import applogo from "../../public/applogo.svg"
import Loder from "../materialUI/Loder"

import styles from '@/styles/Home.module.css'



export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"
/>
       
        
      </Head>
      <div className={styles.main}>
        <Image className={styles.logo} src={applogo} alt='applogo' />
        <Loder />

      </div>
    </>
  )
}
